### ISSUE TITLE
Executing php artisan vendor:publish get the following error

### ISSUE THREAD

**Issue by garauz23** [arvindkumarbadwal/entrust-mongodb#1]
Hi guys, thank you for this package im waiting for it, I have installed and configure mongodb on laravel and is working properly,

php artisan vendor:publish
PHP Fatal error:  Cannot declare class Arvindkumar\EntrustMongoDB\Entrust\EntrustServiceProvider, because the name is already in use in /var/www/core/website/vendor/arvindkumarbadwal/entrust-mongodb/src/Entrust/EntrustServiceProvider.php on line 141

In EntrustServiceProvider.php line 141:

  Cannot declare class Arvindkumar\EntrustMongoDB\Entrust\EntrustServiceProvider, because the name is already in use

**Comment by arvindkumarbadwal** [comment]
Hi,

Thank you for the issue, i had fix the issue.
kindly reinstall the package and also updated readme, fellow the readme.
